/*
 * Copyright (C) 2015 ChristianM
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package vista;

/**
 *
 * @author ChristianM
 */
public class RegistroEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroEmpleado
     */
    public RegistroEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombres = new javax.swing.JLabel();
        lbl_appat = new javax.swing.JLabel();
        lbl_apmat = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        lbl_ndoc = new javax.swing.JLabel();
        lbl_tipodoc = new javax.swing.JLabel();
        cb_tipodoc = new javax.swing.JComboBox();
        txt_nombre = new javax.swing.JTextField();
        txt_appat = new javax.swing.JTextField();
        txt_apmat = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_ndoc = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_tipoemp = new javax.swing.JLabel();
        cb_tipoemp = new javax.swing.JComboBox();
        lbl_sueldo = new javax.swing.JLabel();
        txt_sueldo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registro de Empleados");
        setVisible(true);

        lbl_nombres.setText("Nombres");

        lbl_appat.setText("Apellido paterno");

        lbl_apmat.setText("Apellido materno");

        lbl_direccion.setText("Dirección");

        lbl_correo.setText("Correo");

        lbl_ndoc.setText("N° doc.");

        lbl_tipodoc.setText("Tipo de documento");

        cb_tipodoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_tipodoc.setActionCommand("cb_tipodoc");

        guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guardar.setText("Guardar");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cancelar");

        lbl_tipoemp.setText("Tipo empleado");

        cb_tipoemp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_tipoemp.setActionCommand("cb_tipoemp");

        lbl_sueldo.setText("Sueldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tipodoc)
                    .addComponent(lbl_appat)
                    .addComponent(lbl_apmat)
                    .addComponent(lbl_direccion)
                    .addComponent(lbl_correo)
                    .addComponent(lbl_nombres)
                    .addComponent(lbl_tipoemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_correo)
                    .addComponent(txt_direccion)
                    .addComponent(txt_nombre)
                    .addComponent(txt_apmat)
                    .addComponent(txt_appat)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_tipoemp, javax.swing.GroupLayout.Alignment.LEADING, 0, 121, Short.MAX_VALUE)
                            .addComponent(cb_tipodoc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ndoc)
                            .addComponent(lbl_sueldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ndoc)
                            .addComponent(txt_sueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombres)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_appat)
                    .addComponent(txt_appat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apmat)
                    .addComponent(txt_apmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_correo)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipodoc)
                    .addComponent(cb_tipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ndoc)
                    .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipoemp)
                    .addComponent(cb_tipoemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sueldo)
                    .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbl_nombres.getAccessibleContext().setAccessibleName("lbl_nombres");
        lbl_appat.getAccessibleContext().setAccessibleName("lbl_appat");
        lbl_apmat.getAccessibleContext().setAccessibleName("lbl_apmat");
        lbl_direccion.getAccessibleContext().setAccessibleName("lbl_direccion");
        lbl_correo.getAccessibleContext().setAccessibleName("lbl_correo");
        lbl_ndoc.getAccessibleContext().setAccessibleName("lbl_ndoc");
        lbl_tipodoc.getAccessibleContext().setAccessibleName("lbl_tipodoc");
        cb_tipodoc.getAccessibleContext().setAccessibleName("cb_tipodoc");
        txt_nombre.getAccessibleContext().setAccessibleName("txt_nombre");
        txt_appat.getAccessibleContext().setAccessibleName("txt_appat");
        txt_apmat.getAccessibleContext().setAccessibleName("txt_apmat");
        txt_direccion.getAccessibleContext().setAccessibleName("txt_direccion");
        txt_correo.getAccessibleContext().setAccessibleName("txt_correo");
        txt_ndoc.getAccessibleContext().setAccessibleName("txt_ndoc");
        guardar.getAccessibleContext().setAccessibleName("guardar");
        lbl_tipoemp.getAccessibleContext().setAccessibleName("lbl_tipoemp");
        cb_tipoemp.getAccessibleContext().setAccessibleName("cb_tipoemp");
        lbl_sueldo.getAccessibleContext().setAccessibleName("lbl_sueldo");
        txt_sueldo.getAccessibleContext().setAccessibleName("txt_sueldo");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cb_tipodoc;
    public javax.swing.JComboBox cb_tipoemp;
    public javax.swing.JButton guardar;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel lbl_apmat;
    public javax.swing.JLabel lbl_appat;
    public javax.swing.JLabel lbl_correo;
    public javax.swing.JLabel lbl_direccion;
    public javax.swing.JLabel lbl_ndoc;
    public javax.swing.JLabel lbl_nombres;
    public javax.swing.JLabel lbl_sueldo;
    public javax.swing.JLabel lbl_tipodoc;
    public javax.swing.JLabel lbl_tipoemp;
    public javax.swing.JTextField txt_apmat;
    public javax.swing.JTextField txt_appat;
    public javax.swing.JTextField txt_correo;
    public javax.swing.JTextField txt_direccion;
    public javax.swing.JTextField txt_ndoc;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_sueldo;
    // End of variables declaration//GEN-END:variables
}
